import { contextBridge, ipcRenderer } from "electron";

contextBridge.exposeInMainWorld("agentDesktop", {
  getBootstrap: () => ipcRenderer.invoke("agent:get-bootstrap"),
  saveConfig: (config) => ipcRenderer.invoke("agent:save-config", config),
  listPersonaCards: () => ipcRenderer.invoke("agent:list-persona-cards"),
  createPersonaCard: (input) => ipcRenderer.invoke("agent:create-persona-card", input),
  generatePersonaCardDraft: (input) => ipcRenderer.invoke("agent:generate-persona-card-draft", input),
  updatePersonaCard: (cardId, input) => ipcRenderer.invoke("agent:update-persona-card", cardId, input),
  activatePersonaCard: (cardId) => ipcRenderer.invoke("agent:activate-persona-card", cardId),
  archivePersonaCard: (cardId) => ipcRenderer.invoke("agent:archive-persona-card", cardId),
  restorePersonaCard: (cardId) => ipcRenderer.invoke("agent:restore-persona-card", cardId),
  getMemoryDatabaseStats: () => ipcRenderer.invoke("agent:get-memory-database-stats"),
  listLocalTtsPacks: () => ipcRenderer.invoke("agent:list-local-tts-packs"),
  installLocalTtsPack: (packId) => ipcRenderer.invoke("agent:install-local-tts-pack", packId),
  openLocalTtsFolder: () => ipcRenderer.invoke("agent:open-local-tts-folder"),
  listGptSovitsProfiles: () => ipcRenderer.invoke("agent:list-gpt-sovits-profiles"),
  installGptSovitsProfile: (profileId) => ipcRenderer.invoke("agent:install-gpt-sovits-profile", profileId),
  chat: (payload) => ipcRenderer.invoke("agent:chat", payload),
  searchFiles: (query) => ipcRenderer.invoke("agent:search-files", query),
  getAppRegistry: () => ipcRenderer.invoke("agent:get-app-registry"),
  refreshAppRegistry: () => ipcRenderer.invoke("agent:refresh-app-registry"),
  getRagStatus: () => ipcRenderer.invoke("agent:get-rag-status"),
  rebuildRagIndex: () => ipcRenderer.invoke("agent:rebuild-rag-index"),
  openExternal: (url) => ipcRenderer.invoke("agent:open-external", url),
  getInterestSandbox: () => ipcRenderer.invoke("agent:get-interest-sandbox"),
  getInterestState: () => ipcRenderer.invoke("agent:get-interest-state"),
  cleanupInterestSandbox: (mode) => ipcRenderer.invoke("agent:cleanup-interest-sandbox", mode),
  updateInterestLocation: (location) => ipcRenderer.invoke("agent:update-interest-location", location),
  runInterestActivity: (type) => ipcRenderer.invoke("agent:run-interest-activity", type),
  playInterestGame: (activityId) => ipcRenderer.invoke("agent:play-interest-game", activityId),
  interruptInterestActivity: () => ipcRenderer.invoke("agent:interrupt-interest-activity"),
  openInterestSandbox: () => ipcRenderer.invoke("agent:open-interest-sandbox"),
  openInterestCategory: (category) => ipcRenderer.invoke("agent:open-interest-category", category),
  openInterestArtifact: (artifactPath) => ipcRenderer.invoke("agent:open-interest-artifact", artifactPath)
});
